### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by thebetterjort** [jplew/next-keycloak#1]
Thanks for the repo. I've moved on to Auth0 as the amount of leg lifting on keycloak was too much. I hope to revisit this concept in the future.

**Comment by jplew** [comment]
totally understandable. I came up with this solution for my job, where I inherited a Keycloak backend.

To be frank, Keycloak would probably be my last choice for a UAA if I were developing a new app from scratch. Having to customize the FTL files in a package distinct from my front-end is a pain, plus writing custom hooks requires knowledge of Java. =P

I've heard good things about Auth0, but also had good experiences with Firebase Auth, AWS Amplify etc...

**Comment by biels** [comment]
While those other options are probably easier to set up, it's nice to have the option to do authentication the right way without depending on a third party cloud solution which for some projects may be not okay.
